@startuml

skinparam componentStyle uml2
skinparam component {
  BorderColor #grey
  BackgroundColor #white
}

[Address] <<..address..>>
[Customer] <<..customer..>>
[Order] <<..order..>> #white/PowderBlue
[Tickets] <<..ticket..>> #white/PowderBlue
[Hall] <<..hall..>> as hall
[Seat] <<..seat..>> as seat
[Movie] <<..movie..>> as movie
[Program] <<..program..>> as program #PowderBlue



[Order] ---> [Customer] : is placed by
[Order] --> [Tickets]
[Tickets] --> hall
[Tickets] --> movie
hall -> seat

[Customer] --> [Address]

[Tickets] <--[#green]- program
note top on link #lightgreen: provides test

@enduml
