@startuml

skinparam componentStyle uml2
skinparam component {
  BorderColor #grey
  BackgroundColor #white
}

[Controller] <<..controller..>> as controller #PowderBlue
[Facade] <<..facade..>> as facade #PowderBlue
[Service] <<..service..>> as service #PowderBlue
[Persistence] <<..persistence..>> as persistence #white/PowderBlue

controller ---> service
controller --> facade
facade --> service
service --> persistence




@enduml
